const AllCoursesActionTypes = {
  FETCH_ALL_COURSES_START: 'FETCH_ALL_COURSES_START',
  FETCH_ALL_COURSES_SUCCESS: 'FETCH_ALL_COURSES_SUCCESS',
  FETCH_ALL_COURSES_FAILURE: 'FETCH_ALL_COURSES_FAILURE',
};

export default AllCoursesActionTypes;
