const AssignmentPageActionTypes = {
  FETCH_ASSIGNMENT_START: 'FETCH_ASSIGNMENT_START',
  FETCH_ASSIGNMENT_SUCCESS: 'FETCH_ASSIGNMENT_SUCCESS',
  FETCH_ASSIGNMENT_FAILURE: 'FETCH_ASSIGNMENT_FAILURE',
  SUBMIT_ASSIGNMENT_START: 'SUBMIT_ASSIGNMENT_START',
  SUBMIT_ASSIGNMENT_SUCCESS: 'SUBMIT_ASSIGNMENT_SUCCESS',
  SUBMIT_ASSIGNMENT_FAILURE: 'SUBMIT_ASSIGNMENT_FAILURE',
  RESET_ASSIGNMENT_INFO: 'RESET_ASSIGNMENT_INFO',
};

export default AssignmentPageActionTypes;
