const FeeDetailTypes = {
  FETCH_FEE_DETAILS_START: 'FETCH_FEE_DETAILS_START',
  FETCH_FEE_DETAILS_SUCCESS: 'FETCH_FEE_DETAILS_SUCCESS',
  FETCH_FEE_DETAILS_FAILURE: 'FETCH_FEE_DETAILS_FAILURE',
};

export default FeeDetailTypes;
