const CourseOverviewActionTypes = {
  SET_CURRENT_COURSE_FOR_OVERVIEW: 'SET_CURRENT_COURSE_FOR_OVERVIEW',
  SET_CURRENT_COURSE_FOR_OVERVIEW_FOR_HOME:
    'SET_CURRENT_COURSE_FOR_OVERVIEW_FOR_HOME',
  FETCH_COURSE_FOR_OVERVIEW_START: 'FETCH_COURSE_FOR_OVERVIEW_START',
  FETCH_COURSE_FOR_OVERVIEW_SUCCESS: 'FETCH_COURSE_FOR_OVERVIEW_SUCCESS',
  FETCH_COURSE_FOR_OVERVIEW_FAILURE: 'FETCH_COURSE_FOR_OVERVIEW_FAILURE',
  FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_START:
    'FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_START',
  FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_SUCCESS:
    'FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_SUCCESS',
  FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_FAILURE:
    'FETCH_COURSE_FOR_OVERVIEW_FOR_HOME_FAILURE',
};

export default CourseOverviewActionTypes;
