const FeeAmountTypes = {
  FETCH_FEE_AMOUNT_START: 'FETCH_FEE_AMOUNT_START',
  FETCH_FEE_AMOUNT_SUCCESS: 'FETCH_FEE_AMOUNT_SUCCESS',
  FETCH_FEE_AMOUNT_FAILURE: 'FETCH_FEE_AMOUNT_FAILURE',
};

export default FeeAmountTypes;
