const CourseTopicActionTypes = {
  FETCH_COURSE_TOPICS_START: 'FETCH_COURSE_TOPICS_START',
  FETCH_COURSE_TOPICS_SUCCESS: 'FETCH_COURSE_TOPICS_SUCCESS',
  FETCH_COURSE_TOPICS_FAILURE: 'FETCH_COURSE_TOPICS_FAILURE',
  VIEWED_LECTURE_FOR_FIRST_TIME_START: 'VIEWED_LECTURE_FOR_FIRST_TIME_START',
  VIEWED_LECTURE_FOR_FIRST_TIME_SUCCESS:
    'VIEWED_LECTURE_FOR_FIRST_TIME_SUCCESS',
  VIEWED_LECTURE_FOR_FIRST_TIME_FAILURE:
    'VIEWED_LECTURE_FOR_FIRST_TIME_FAILURE',
};

export default CourseTopicActionTypes;
