const CourseOverviewActionTypes = {
  SET_CURRENT_COURSE_FOR_OVERVIEW: 'SET_CURRENT_COURSE_FOR_OVERVIEW',
  FETCH_COURSE_FOR_OVERVIEW_START: 'FETCH_COURSE_FOR_OVERVIEW_START',
  FETCH_COURSE_FOR_OVERVIEW_SUCCESS: 'FETCH_COURSE_FOR_OVERVIEW_SUCCESS',
  FETCH_COURSE_FOR_OVERVIEW_FAILURE: 'FETCH_COURSE_FOR_OVERVIEW_FAILURE',
};

export default CourseOverviewActionTypes;
