const StudentActionTypes = {
  FETCH_ENROLLED_COURSES_START: 'FETCH_ENROLLED_COURSES_START',
  FETCH_ENROLLED_COURSES_SUCCESS: 'FETCH_ENROLLED_COURSES_SUCCESS',
  FETCH_ENROLLED_COURSES_FAILURE: 'FETCH_ENROLLED_COURSES_FAILURE',
  SET_CURRENT_COURSE: 'SET_CURRENT_COURSE',
  SET_CURRENT_COURSE_TOPIC_CONTENT: 'SET_CURRENT_COURSE_TOPIC_CONTENT',
};

export default StudentActionTypes;
