const questionData = {
  assignment: {
    questions: [
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '1',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['opt2'],
        options: ['opt1', 'opt2', 'opt3', 'opt4'],
        _id: '5fdaeb7148414a30a80c3b94',
        type: 'SINGLECORRECT',
        number: '2',
        name: 'dummy',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '3',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '4',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '5',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '6',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '7',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '8',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '9',
        statement: 'correct option 2',
        maxMarks: 10,
        __v: 0,
      },
      {
        correctAns: ['test2'],
        options: ['test1', 'test2', 'test3', 'test4'],
        _id: '5fa6b84511ef256644d5afaf',
        type: 'SINGLECORRECT',
        number: '10',
        statement: 'second is the corret option',
        maxMarks: 10,
        __v: 0,
      },
    ],
    _id: '5fdaecf25aa95631647c4089',
    subjectCode: 'T1011',
    subjectName: 'Dummy',
    assignmentName: 'dummyass',
    duration: 30,
    maxMarks: 100,
    __v: 0,
  },
  attemptsLeft: 3,
};

export default questionData;
